use serde_json::{Value, json};

use super::spec::KitSpec;

/// The output artifacts generated by the `KitGenerator`.
///
/// These artifacts represent the complete UI kit and can be used to configure
/// a compatible frontend or serve as design documentation.
#[derive(Debug, Clone)]
pub struct KitArtifacts {
    /// The component catalog definition (JSON schema).
    pub catalog: Value,

    /// Design tokens (colors, typography, spacing) as a JSON object.
    pub tokens: Value,

    /// Templates included in the kit.
    pub templates: Value,

    /// CSS variables defining the kit's theme (e.g., `:root { --adk-primary: ... }`).
    pub theme_css: String,
}

/// A generator that produces UI kit artifacts from a specification.
///
/// The `KitGenerator` transforms a high-level `KitSpec` into concrete implementation details
/// like CSS variables, JSON catalogs, and design tokens.
///
/// # Example
///
/// ```rust
/// use adk_ui::kit::{KitGenerator, KitSpec};
///
/// let spec = KitSpec::default();
/// let artifacts = KitGenerator::new().generate(&spec);
/// println!("Theme CSS: {}", artifacts.theme_css);
/// ```
#[derive(Debug, Default)]
pub struct KitGenerator;

impl KitGenerator {
    /// Creates a new `KitGenerator`.
    pub fn new() -> Self {
        Self
    }

    /// Generates kit artifacts from the provided specification.
    ///
    /// This method processes the `KitSpec` and returns a `KitArtifacts` struct containing:
    /// - A unique catalog ID based on the kit name and version.
    /// - A JSON representation of the component catalog.
    /// - Design tokens for colors, typography, density, and radius.
    /// - CSS variables for theming.
    pub fn generate(&self, spec: &KitSpec) -> KitArtifacts {
        let catalog_id = format!("zavora.ai:adk-ui/kit/{}@{}", slugify(&spec.name), spec.version);

        let catalog = json!({
            "": "https://json-schema.org/draft/2020-12/schema",
            "": catalog_id,
            "title": format!("ADK-UI Kit: {}", spec.name),
            "description": format!("Generated UI kit for {}", spec.name),
            "catalogId": catalog_id,
            "components": {},
            "theme": {
                "primaryColor": spec.colors.primary,
                "agentDisplayName": spec.name
            }
        });

        let tokens = json!({
            "colors": {
                "primary": spec.colors.primary,
                "accent": spec.colors.accent,
                "surface": spec.colors.surface,
                "background": spec.colors.background,
                "text": spec.colors.text
            },
            "typography": {
                "family": spec.typography.family,
                "scale": spec.typography.scale
            },
            "density": format!("{:?}", spec.density).to_lowercase(),
            "radius": format!("{:?}", spec.radius).to_lowercase()
        });

        let templates = json!({
            "templates": spec.templates
        });

        let theme_css = format!(
            ":root {{\n  --adk-primary: {};\n  --adk-font-family: \"{}\";\n}}\n",
            spec.colors.primary, spec.typography.family
        );

        KitArtifacts { catalog, tokens, templates, theme_css }
    }
}

fn slugify(input: &str) -> String {
    let mut out = String::new();
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else if (ch.is_whitespace() || ch == '-' || ch == '_') && !out.ends_with('-') {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kit::spec::{KitBrand, KitColors, KitSpec, KitTypography};

    #[test]
    fn generates_catalog_with_expected_id() {
        let spec = KitSpec {
            name: "Fintech Pro".to_string(),
            version: "0.1.0".to_string(),
            brand: KitBrand { vibe: "trustworthy".to_string(), industry: None },
            colors: KitColors {
                primary: "#2F6BFF".to_string(),
                accent: None,
                surface: None,
                background: None,
                text: None,
            },
            typography: KitTypography { family: "Source Sans 3".to_string(), scale: None },
            density: Default::default(),
            radius: Default::default(),
            components: Default::default(),
            templates: vec!["auth_login".to_string()],
        };

        let artifacts = KitGenerator::new().generate(&spec);
        assert_eq!(artifacts.catalog["catalogId"], "zavora.ai:adk-ui/kit/fintech-pro@0.1.0");
        assert!(artifacts.tokens["colors"]["primary"].is_string());
    }
}
